### ISSUE TITLE
undefined method `call' for #<Set: {}>

### ISSUE THREAD

**Issue by LimeBlast** [krisleech/wisper-rspec#11]
I'm not sure if this is something that I'm doing wrong, but I'm having some trouble making this work. Here is my code:

```ruby
require 'spec_helper'
require 'wisper'

require_relative '../../app/commands/create_presentation'

RSpec.describe CreatePresentation do
  let(:form) { double('Form', valid?: valid?) }
  subject do
    command = described_class.new(form)
    command.execute
  end

  context 'valid form' do
    let(:valid?) { true }

    it 'broadcasts :create_presentation_successful' do
      expect(subject).to broadcast(:create_presentation_successful)
    end
  end
end
```

```ruby
class CreatePresentation
  include Wisper::Publisher

  attr_reader :form

  def initialize(form)
    @form = form
  end

  def execute
    if form.valid?
      broadcast(:create_presentation_successful)
    else
      broadcast(:create_presentation_failed, form)
    end
  end
end
```

When I fun the test, I get the following:

```
  1) CreatePresentation valid form broadcasts :create_presentation_successful
     Failure/Error: expect(subject).to broadcast(:create_presentation_successful)
     NoMethodError:
       undefined method `call' for #<Set: {}>
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-rspec-0.0.2/lib/wisper/rspec/matchers.rb:42:in `block in matches?'
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-1.6.0/lib/wisper/temporary_listeners.rb:18:in `subscribe'
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-1.6.0/lib/wisper/temporary_listeners.rb:7:in `subscribe'
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-1.6.0/lib/wisper.rb:45:in `subscribe'
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-rspec-0.0.2/lib/wisper/rspec/matchers.rb:41:in `matches?'
     # ./spec/commands/create_presentation_spec.rb:17:in `block (3 levels) in <top (required)>'
```

Any ideas? Cheers.

UPDATE: I've pushed my code here: https://github.com/LimeBlast/playing_with_wisper_gem

**Comment by krisleech** [comment]
You are using wisper 1.6 which has RSpec matchers included. The RSpec matchers where moved out of Wisper in to a separate gem in release candidate for 2.0 and are only required if you are using that version. 

The README you see, which directs you to the wisper-rspec gem is the README for 2.0.0.rc1, you can see the 1.6 README [here](https://github.com/krisleech/wisper/tree/v1.6.0#rspec)

I'd suggest either remove `wisper-rspec` from `Gemfile` and refer to the README linked above, or change wisper to `2.0.0.rc1` which in most cases is backwards compatible.

Hope this helps.

**Comment by LimeBlast** [comment]
I did wonder why both gems folders contained matcher code. I'll give that a try, thank you.

**Comment by LimeBlast** [comment]
I updated wisper to `2.0.0.rc1`, but was still getting an error - this one was different though:

```
  1) CreatePresentation valid form broadcasts :create_presentation_successful
     Failure/Error: expect(described_class.new(form).execute).to broadcast(:create_presentation_successful)
     NoMethodError:
       undefined method `call' for #<CreatePresentation:0x000000026dbee0>
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-rspec-0.0.2/lib/wisper/rspec/matchers.rb:42:in `block in matches?'
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-2.0.0.rc1/lib/wisper/temporary_listeners.rb:20:in `subscribe'
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-2.0.0.rc1/lib/wisper/temporary_listeners.rb:9:in `subscribe'
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-2.0.0.rc1/lib/wisper.rb:30:in `subscribe'
     # /home/daniel/.rvm/gems/ruby-2.2.2/gems/wisper-rspec-0.0.2/lib/wisper/rspec/matchers.rb:41:in `matches?'
     # ./spec/commands/create_presentation_spec.rb:13:in `block (3 levels) in <top (required)>'
```

They key difference being `undefined method 'call' for #<CreatePresentation:0x000000026dbee0>` - so I've updated my code as such:

```ruby
class CreatePresentation
  include Wisper::Publisher

  attr_reader :form

  def initialize(form)
    @form = form
  end

  def call
    if form.valid?
      broadcast(:create_presentation_successful)
    else
      broadcast(:create_presentation_failed, form)
    end
  end
end
```

```ruby
require 'spec_helper'
require 'wisper'

require_relative '../../app/commands/create_presentation'

RSpec.describe CreatePresentation do
  let(:form) { double('Form', valid?: valid?) }

  context 'valid form' do
    let(:valid?) { true }

    it 'broadcasts :create_presentation_successful' do
      expect(described_class.new(form)).to broadcast(:create_presentation_successful)
    end
  end

  context 'not valid form' do
    let(:valid?) { false }

    it 'broadcasts :create_presentation_failed' do
      expect(described_class.new(form)).to broadcast(:create_presentation_failed, form)
    end
  end
end
```

and it seems to work correctly now.

They key differences are that in my original class I was using `.execute()` (which I got from the [wiki on command objects](https://github.com/krisleech/wisper/wiki/Command-Object)), which I've now updated to `.call()`, and in my spec, I'm no longer explicitly calling `.call()`... does this sound about right?

As I say, it appears to be working, but I just want to check I'm not doing something stupid.

**Comment by krisleech** [comment]
You shouldn't have to change the method name from `execute` to `call`, the matcher should not require a specific method.

Ah, I spotted what might be the problem, you are doing `expect(...).to broadcast(...)` it should be `expect { ... }.to broadcast(...)`.

This is because the matcher needs a block to yield.

**Comment by LimeBlast** [comment]
Ah, that makes much more sense, and indeed seems to work as intended, my code now looks like this (including the important job of actually creating the presentation):

```ruby
class CreatePresentation
  include Wisper::Publisher

  attr_reader :form

  def initialize(form)
    @form = form
  end

  def call
    if form.valid?
      presentation = Presentation.create(form.attributes)
      broadcast(:create_presentation_successful, presentation)
    else
      broadcast(:create_presentation_failed, form)
    end
  end
end
```

```ruby
require 'spec_helper'
require 'wisper'

require_relative '../../app/commands/create_presentation'

RSpec.describe CreatePresentation do
  let(:form) { double('Form', valid?: valid?, attributes: attributes) }
  let(:attributes) { {} }

  context 'valid form' do
    let(:valid?) { true }
    let(:presentation_class) { class_double('Presentation').as_stubbed_const }
    let(:presentation_object) { double }

    before :each do
      expect(presentation_class).to receive(:create).with(attributes).and_return(presentation_object)
    end

    it 'broadcasts :create_presentation_successful' do
      expect { described_class.new(form).call }.to broadcast(:create_presentation_successful)
    end
  end

  context 'not valid form' do
    let(:valid?) { false }

    it 'broadcasts :create_presentation_failed and return the form' do
      expect { described_class.new(form).call }.to broadcast(:create_presentation_failed, form)
    end
  end
end
```

To stick with rails convention, I've retained the `'call()` on my object, but switched expect to use a block, explicitly calling `.call()` inside it, and it's all passing - how does this look?

Thank you.

**Comment by krisleech** [comment]
No problem, that looks good :smile:
