### ISSUE TITLE
NameError: uninitialized constant RSpec::Mocks::ExampleMethods after upgrade to v0.0.3

### ISSUE THREAD

**Issue by wojtha** [krisleech/wisper-rspec#20]
It fails when I run rspec directly e.g. `bundle exec rspec` but the error does not emerge when I use `zeus` where all code is preloaded in advance.

It fails on this line:

```ruby
# spec/support/config/factory_girl.rb
FactoryGirl::SyntaxRunner.include(RSpec::Mocks::ExampleMethods)
```

The spec_helper begins like this

```ruby
# spec/spec_helper.rb
require 'rubygems'
require 'rails/application'
require_relative '../config/environment.rb'
require 'rspec/rails'
require 'factory_girl'
require 'rspec/collection_matchers'
require 'rspec/instafail'
require 'wisper/rspec/matchers'

Dir[Rails.root.join('spec/support/**/*.rb')].sort.each { |f| require f }

RSpec.configure do |config|
  # ...
end
```

I was trying to require the RSpec::Mocks::ExampleMethods before this line to fix this but without luck. Downgrading to wisper-rspec 0.0.2 resolves the issue.

**Environment**

- ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]
- rails 4.1.16
- rspec-rails 3.5.2
- wisper 2.0.0.rc1
- wisper-rspec 0.0.3

**Stacktrace**

```
NameError: uninitialized constant RSpec::Mocks::ExampleMethods
  /Users/wojtha/Code/portal/spec/support/config/factory_girl.rb:3:in `<top (required)>'
  /Users/wojtha/Code/portal/spec/spec_helper.rb:64:in `block in <top (required)>'
  /Users/wojtha/Code/portal/spec/spec_helper.rb:64:in `each'
  /Users/wojtha/Code/portal/spec/spec_helper.rb:64:in `<top (required)>'
  /Users/wojtha/Code/portal/spec/adapters/contact_adapter_spec.rb:1:in `require'
  /Users/wojtha/Code/portal/spec/adapters/contact_adapter_spec.rb:1:in `<top (required)>'
  /Users/wojtha/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  /Users/wojtha/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /Users/wojtha/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  /Users/wojtha/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /Users/wojtha/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  /Users/wojtha/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  /Users/wojtha/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /Users/wojtha/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/wojtha/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /Users/wojtha/.rbenv/versions/2.3.3/bin/rspec:22:in `load'
  /Users/wojtha/.rbenv/versions/2.3.3/bin/rspec:22:in `<top (required)>'
```

**Comment by krisleech** [comment]
I'm not sure how this is related to wisper, any ideas?

**Comment by lazyatom** [comment]
I think the comment I left on #21 addresses this too; basically there's a subtle assumption within Rspec  that if the `Rspec::Mocks` constant is present, then the whole of that library has been loaded, but if another mocking framework has been selected, this won't be the case.

**Comment by krisleech** [comment]
@lazyatom Thing is it looks like it is failing before wisper/rspec is even required, I wonder if @wojtha can confirm?

**Comment by krisleech** [comment]
This has now been fixed in RSpec.
